### ISSUE TITLE
项目构建真是复杂

### ISSUE THREAD

**Issue by GaoMjun** [shadowsocks/Potatso-iOS#12]
搞了一天终于好了。

给需要的人参考

0. Apple 开发者账号，NetworkExtension 权限

1. git submodule update --init 
2. 修改 './Library/Aspects/Aspects.podspec' 和 
		'./Library/ICSMainFramework/ICSMainFramework.podspec' 的 
		s.source 为 { :path => "." }
3. 修改 Podfile 中 'TodayWidget' target, `pod 'SwiftColor'` -> pod 'SwiftColor', '~> 0.3.7'
4. pod update
6. carthage update
7. 修改 Potatso, PacketTunnel, TodayWidget 三个 Target 的 Bundle Identifier
8. 关闭 Capabilites 中的 Push Notification 和 Background Modes
9. 去掉 App Group 原来的钩，先建一个 group 并打钩，三个 Target 同样
10. 去开发者中心先建三个 profile，选择 NetworkExtension （这个只要申请到 NetworkExtension 权限才有）
11. 修改 PacketTunnel/PacketTunnelProvider.m 中 initWithApplicationGroupIdentifier 的 identifier 
12. 打完收工

**Comment by Ryan0520** [comment]
项目构建确实太复杂，弄了好久也没能运行成功。。

**Comment by FlowerWrong** [comment]
1. Apple 开发者账号，NetworkExtension 权限
2. `git submodule update --init`
3. install pod 0.39 with ruby 2.2.5（<2.3） and then `pod install`
4. carthage _update(国内如果下载不下来用master分支，release会从aws下载)
5. 修改 Potatso, PacketTunnel, TodayWidget 三个 Target 的 Bundle Identifier
6. 关闭 Capabilites 中的 Push Notification 和 Background Modes
7. 去掉 App Group 原来的钩，先建一个 group 并打钩，三个 Target 同样
8. 去开发者中心先建三个 profile，选择 NetworkExtension （这个只要申请到 NetworkExtension 权限才有）
9. 搜索并体会app group identifier

**Comment by icodesign** [comment]
这个工程的确需要一定的 iOS 开发经验才能 setup 起来

**Comment by Ryan0520** [comment]
感觉这个都可以用于来测试开发者的年限水平了。。。。

**Comment by FlowerWrong** [comment]
感觉iOS项目好难github协作

**Comment by icodesign** [comment]
@FlowerWrong 那倒不是，主要是：
1. 我还没弄自动化构建的脚本
2. 这个项目要求不少证书

**Comment by hello--world** [comment]
哈哈，看来之前的折腾是值的，昨天没一会就运行起来了。但，NetworkExtension需要申请什么些功能，昨天看了有好多选项。

**Comment by DJBen** [comment]
作者可以考虑下 [fastlane](https://fastlane.tools) 这样的命令行式自动管理证书 ＋ build 的工具来简化这个头疼的人工流程

**Comment by icodesign** [comment]
@DJBen 我本地确实用 fastlane 来自动化管理的，但是由于我的 fastlane 涉及到一些隐私信息，所以没有放出，我会慢慢补上 build 脚本的

**Comment by lsy530371279** [comment]
![image](https://cloud.githubusercontent.com/assets/17850429/17327411/684e13e2-58ea-11e6-8923-b12f837dfd8d.png)


按上述步骤操作后，反而出了这些问题

**Comment by monsterChen** [comment]
按照@GaoMjun的方法尝试了，出现了KeychainAccess报错，将其版本更改为2.3.0，报错消失。
但Cartography尝试了多个版本还是报错。
跟个过程中每次pod update都会出现相关“Use the `$(inherited)` flag, or”的警告。
请问是什么问题？
[!] There are duplicate dependencies on `Cartography` in `Podfile`:

- Cartography
- Cartography (~> 0.1.0)

[!] The `Potatso [Debug]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Potatso/Pods-Potatso.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Potatso [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-Potatso/Pods-Potatso.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Potatso [Release]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-Potatso/Pods-Potatso.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Potatso [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-Potatso/Pods-Potatso.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `TodayWidget [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-TodayWidget/Pods-TodayWidget.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `TodayWidget [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-TodayWidget/Pods-TodayWidget.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `PotatsoLibrary [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-PotatsoLibrary/Pods-PotatsoLibrary.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `PotatsoLibrary [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-PotatsoLibrary/Pods-PotatsoLibrary.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `PotatsoModel [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-PotatsoModel/Pods-PotatsoModel.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `PotatsoModel [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-PotatsoModel/Pods-PotatsoModel.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by qinxianjun** [comment]
@GaoMjun @icodesign 申请权限需要多久啊？

**Comment by qinxianjun** [comment]
@GaoMjun @FlowerWrong 你们编译成功了嘛？我基础差，能指导指导嘛？企鹅791085038

**Comment by GaoMjun** [comment]
@qinxianjun 我好久没搞了，估计现在工程应该变了很多，还是得一步步看到错误解决错误，直到编译成功。

**Comment by qinxianjun163** [comment]
@GaoMjun 参考步骤的第二步到第六步需要在终端完成嘛？

**Comment by aishuidedabai** [comment]
能否发一份借鉴一下，被逼疯了，1404019775@qq.com
