### ISSUE TITLE
Fabric 

### ISSUE THREAD

**Issue by ChaosTong** [shadowsocks/Potatso-iOS#16]
Print: Entry, ":FabricSecret", Does Not Exist
/Users/chaos/Developer/Potatso-iOS/Pods/Fabric/run: eval: line 18: unexpected EOF while looking for matching `''
/Users/chaos/Developer/Potatso-iOS/Pods/Fabric/run: eval: line 19: syntax error: unexpected end of file
Command /bin/sh failed with exit code 1

**Comment by GaoMjun** [comment]
Fabric 的东西可以都删掉

**Comment by ChaosTong** [comment]
终于弄好了，被证书搞炸了
The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. (0xE8008016).
遇见这个我问题的朋友，请在Capabilities 中打开KeyChain Sharing 添加
com.apple.managed.vpn.shared
"你的AppleID prefix".*

问题是怎么产生的呢，就是我申请时的id prefix，和现在生成的provisioning 上的id prefix 不一致
具体细节可以看之前shadowsock作者没写完的shadowVPN里找

**Comment by ChandlerPang** [comment]
工程下载下来后没有办法编译，你们用的自己的开发ID么？
