### ISSUE TITLE
domain match google代理无效(非全局)

### ISSUE THREAD

**Issue by FlowerWrong** [shadowsocks/Potatso-iOS#18]
如果我不开全局代理，domain match google无效。截图如下。
![1 pic](https://cloud.githubusercontent.com/assets/5362640/16401174/def16f54-3d14-11e6-955b-a5e0392ab4aa.jpg)

![3 pic](https://cloud.githubusercontent.com/assets/5362640/16401195/18d622aa-3d15-11e6-87e6-c4ffe8dee729.jpg)

**Comment by icodesign** [comment]
这个情况不是规则的问题，好像是代理没起来，你重启 Potatso 试试？

**Comment by ANDREW3861** [comment]
Wang friend I don't understand

**Comment by icodesign** [comment]
你是从 Today Widget 启动 VPN 的吗

**Comment by FlowerWrong** [comment]
@icodesign 

> 你是从 Today Widget 启动 VPN 的吗

不是，我试过多次了都无效，我猜是DNS的问题。不过我不会debug。
![1 pic](https://cloud.githubusercontent.com/assets/5362640/16410471/32949934-3d55-11e6-89ba-c87d73fa8a21.jpg)

**Comment by FlowerWrong** [comment]
@icodesign 我直接https://google.com.hk是可以的，但是https://google.com不行。

**Comment by FlowerWrong** [comment]
@icodesign 能否解释一下app的数据流结构。我试着画了下。不明白http proxy和utun的关系。数据到底是过http proxy还是utun。[NEIPv4Settings/includedRoutes](https://developer.apple.com/library/ios/documentation/NetworkExtension/Reference/NEIPv4SettingsClassRef/index.html#//apple_ref/occ/instp/NEIPv4Settings/includedRoutes) 这里有说includedRoutes配置的会过utun。
我画的结构图如下(箭头表示数据流向)：
![iosnet](https://cloud.githubusercontent.com/assets/5362640/16476760/20d4d042-3ebd-11e6-9c6e-5796f9efdac3.png)

**Comment by ANDREW3861** [comment]
Andrew Thaddeus brown
