### ISSUE TITLE
最新TF版在导入无效文件时会闪退

### ISSUE THREAD

**Issue by automan000** [shadowsocks/Potatso-iOS#24]
RT，从URL导入时直接闪退

**Comment by icodesign** [comment]
URL: https://files.deductive.cf/?secret=o1MGRXWVRHWNxmUxpFbCpmWxUkMWtmUaRmaKN0UxIUekVkUGdFVJZXZWdGNNhUSxYVb4QjYqhmROpmR4NGVKhUYr10dhBDbFJlVsNjYUdWMOdUVx0EbnhnWs5kUhJjSERGRWhkYqRWbW5WR6d1V0ZjVHhmNNREZQ1kROdlVWJ1aSREbO1kbK9UTVJ1TjdFbV1EWKJ0VVp0SZRlSzdlas5UYtZVdZxmWIFGbVNjYFZUYhFjUNdlbOJDZEVFeTpWT04kMkJkYqJUVTdFNyQWVGRjWwQ2QRBTRxIWRktWWXJFWNBjRN90RzFjVHR2bkdVW08EVsB3UrhmSUJTSxMVMWZVTYhmQOVUOy4kbadlWGRWWPZ1YzIFM4VjTuVEMiFTTwwUMjJDTyUVeUNjT00kbGFWTFBHWXVUVyRFVCVzUtpUVPZUQwU1a1MTZplzMTh0b
