### ISSUE TITLE
'CocoaAsyncSocket' not found 这是什么原因

### ISSUE THREAD

**Issue by bf68** [shadowsocks/Potatso-iOS#31]
@import CocoaAsyncSocket; not found

/Users/mac/Downloads/Potatso-iOS-master/PacketProcessor/TunnelInterface.m:17:9: Module 'CocoaAsyncSocket' not found

**Comment by icodesign** [comment]
[Setup Guide](../wiki/SetupGuide)

**Comment by maomihz** [comment]
按说明配置好开发环境后要打开Potatso.xcworkspace而不是Potatso.xcodeproj，不然就会有找不到Framework/Module的问题
